# Changes here will be overwritten by Copier
_commit: v0.0.5-5-g3b9fe32
_src_path: gh:LabAutomationAndScreening/copier-python-package-template
create_docs: false
description: Agent to upload files to cloud
full_repo_url: https://github.com/LabAutomationAndScreening/cloud-courier
is_frozen_executable: true
package_name: cloud-courier
primary_author: Eli Fine
python_ci_versions:
- 3.12.7
python_version: 3.12.7
repo_name: cloud-courier
repo_org_name: LabAutomationAndScreening
ssh_port_number: 61020
use_windows_in_ci: true

