version: '3.8'
services:
  devcontainer:
    build:
      context: .
      args:
        REPO_NAME: cloud-courier
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/cloud-courier:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts
      - python_venv:/workspaces/cloud-courier/.venv
    command: sleep infinity
    ports:
      - "61020:2222"
    environment:
      - AWS_PROFILE=localstack
      - AWS_DEFAULT_REGION=

  localstack:
    image: localstack/localstack:4.1.1 # no known reason for not using newer versions, just pinning for best practice
    container_name: localstack
    ports:
      - "4566:4566"  # Main edge port for all AWS service emulation
    environment:
      - SERVICES=s3,ssm,iam,sts

volumes:
  python_venv: {}
